apiVersion: kustomize.config.k8s.io/v1beta1
labels:
- pairs:
    app.kubernetes.io/name: existing-single-inrepo-port-ingress-autodeploy-20250902180147
    app: existing-single-inrepo-port-ingress-autodeploy-20250902180147
configMapGenerator:
- name: existing-single-inrepo-port-ingress-autodeploy-20250902180147-environment-values
  envs:
  - environment-values.env
- name: existing-single-inrepo-port-ingress-autodeploy-20250902180147-container-vars
  envs:
  - container.env
generatorOptions:
  disableNameSuffixHash: true # use a static name
kind: Kustomization
resources:
- deployment.yaml
- service.yaml